/** Ch 3 Membrane Transport — flashcard deck (35 cards) */
export const FLASHCARD_TAGS = ["Biology", "CellMembrane", "Transport"];

export const FLASHCARD_DECK = [
  // Subtopic 1: Fluid Mosaic Model
  {
    id: 1,
    subtopic: "Fluid Mosaic Model",
    front: 'In the Fluid Mosaic Model, what does "<strong>fluid</strong>" mean?',
    back: "The <strong>phospholipid bilayer</strong> can move <strong>laterally</strong>.",
    image: "./assets/page01_img2.jpeg",
    imageAlt: "Fluid mosaic model — phospholipid bilayer with embedded proteins",
  },
  {
    id: 2,
    subtopic: "Fluid Mosaic Model",
    front: 'In the Fluid Mosaic Model, what does "<strong>mosaic</strong>" mean?',
    back: "<strong>Membrane proteins</strong> are embedded in a mosaic pattern.",
    image: "./assets/page01_img2.jpeg",
    imageAlt: "Mosaic pattern of membrane proteins in the bilayer",
  },
  {
    id: 3,
    subtopic: "Fluid Mosaic Model",
    front: "Which part of a phospholipid is <strong>hydrophilic</strong> (polar)?",
    back: "The <strong>phosphate head</strong>.",
    image: "./assets/page08_img1.jpeg",
    imageAlt: "Phospholipid molecule — hydrophilic head and hydrophobic tails",
  },
  {
    id: 4,
    subtopic: "Fluid Mosaic Model",
    front: "Which part of a phospholipid is <strong>hydrophobic</strong> (non-polar)?",
    back: "The <strong>fatty acid tails</strong>.",
    image: "./assets/page08_img1.jpeg",
    imageAlt: "Phospholipid molecule — hydrophobic fatty acid tails",
  },
  {
    id: 5,
    subtopic: "Fluid Mosaic Model",
    front: "How are phospholipids arranged in the cell membrane?",
    back: 'In a "<strong>tail-to-tail</strong>" bilayer.',
    image: "./assets/page08_img2_bilayer.jpeg",
    imageAlt: "Phospholipid bilayer — extracellular fluid, cytoplasm, tail-to-tail tails",
  },
  {
    id: 6,
    subtopic: "Fluid Mosaic Model",
    front: "What is the function of <strong>receptor proteins</strong>?",
    back: 'Act as "<strong>card readers</strong>" to bind chemical messengers (e.g., hormones).',
    image: "./assets/page09_img3.jpeg",
    imageAlt: "Membrane proteins including receptor proteins",
  },
  {
    id: 7,
    subtopic: "Fluid Mosaic Model",
    front: "What is the function of <strong>glycoproteins</strong>?",
    back: 'Act as an "<strong>ID Card</strong>" (antigen) for cell identification.',
    image: "./assets/page09_img3.jpeg",
    imageAlt: "Glycoproteins for cell recognition and identification",
  },

  // Subtopic 2: Permeability & Specific Substances
  {
    id: 8,
    subtopic: "Permeability & Specific Substances",
    front: "How does <strong>oxygen</strong> cross the cell membrane?",
    back: "Direct diffusion via the <strong>phospholipid bilayer</strong> (small, non-polar).",
    image: "./assets/page02_img2.jpeg",
    imageAlt: "Differential permeability — small non-polar molecules through bilayer",
  },
  {
    id: 9,
    subtopic: "Permeability & Specific Substances",
    front: "How does <strong>carbon dioxide</strong> cross the cell membrane?",
    back: "Direct diffusion via the <strong>phospholipid bilayer</strong> (small, non-polar).",
    image: "./assets/page02_img2.jpeg",
    imageAlt: "Differential permeability diagram",
  },
  {
    id: 10,
    subtopic: "Permeability & Specific Substances",
    front: "How do <strong>fatty acids</strong> cross the cell membrane?",
    back: "Direct diffusion via the <strong>phospholipid bilayer</strong> (lipid-soluble / non-polar).",
    image: "./assets/page02_img2.jpeg",
    imageAlt: "Differential permeability diagram",
  },
  {
    id: 11,
    subtopic: "Permeability & Specific Substances",
    front: "How does <strong>glycerol</strong> cross the cell membrane?",
    back: "Direct diffusion via the <strong>phospholipid bilayer</strong> (small, non-polar).",
    image: "./assets/page02_img2.jpeg",
    imageAlt: "Differential permeability diagram",
  },
  {
    id: 12,
    subtopic: "Permeability & Specific Substances",
    front: "How does <strong>water</strong> cross the cell membrane?",
    back: "Via <strong>membrane proteins</strong> (small, polar).",
    image: "./assets/page02_img2.jpeg",
    imageAlt: "Water crossing via channel or carrier proteins",
  },
  {
    id: 13,
    subtopic: "Permeability & Specific Substances",
    front: "How do <strong>amino acids</strong> cross the cell membrane?",
    back: "Via <strong>membrane proteins</strong> (small, polar).",
    image: "./assets/page02_img2.jpeg",
    imageAlt: "Polar molecules via membrane proteins",
  },
  {
    id: 14,
    subtopic: "Permeability & Specific Substances",
    front: "How does <strong>glucose</strong> cross the cell membrane?",
    back: "Via <strong>membrane proteins</strong> (small, polar).",
    image: "./assets/page02_img2.jpeg",
    imageAlt: "Glucose via carrier proteins",
  },
  {
    id: 15,
    subtopic: "Permeability & Specific Substances",
    front: "How do <strong>sodium</strong> ions cross the cell membrane?",
    back: "Via <strong>membrane proteins</strong> (small, charged).",
    image: "./assets/page02_img2.jpeg",
    imageAlt: "Ions via channel proteins",
  },
  {
    id: 16,
    subtopic: "Permeability & Specific Substances",
    front: "How do <strong>calcium</strong> ions cross the cell membrane?",
    back: "Via <strong>membrane proteins</strong> (small, charged).",
    image: "./assets/page02_img2.jpeg",
    imageAlt: "Ions via channel proteins",
  },
  {
    id: 17,
    subtopic: "Permeability & Specific Substances",
    front: "How does <strong>starch</strong> cross the cell membrane?",
    back: "Via <strong>membrane folding</strong> (large molecule).",
    image: "./assets/page02_img2.jpeg",
    imageAlt: "Large molecules blocked — membrane folding required",
  },
  {
    id: 18,
    subtopic: "Permeability & Specific Substances",
    front: "How do <strong>triglycerides</strong> cross the cell membrane?",
    back: "Via <strong>membrane folding</strong> (large molecule).",
    image: "./assets/page02_img2.jpeg",
    imageAlt: "Large molecules blocked by bilayer",
  },
  {
    id: 19,
    subtopic: "Permeability & Specific Substances",
    front: "How do large <strong>proteins</strong> cross the cell membrane?",
    back: "Via <strong>membrane folding</strong> (large molecule).",
    image: "./assets/page02_img2.jpeg",
    imageAlt: "Large proteins require membrane folding",
  },
  {
    id: 20,
    subtopic: "Permeability & Specific Substances",
    front: "How do <strong>organic solvents</strong> (like alcohol) damage the cell membrane?",
    back: "They <strong>dissolve the lipid bilayer</strong> and <strong>denature proteins</strong>.",
    image: "./assets/page10_img1.jpeg",
    imageAlt: "Beetroot ethanol experiment — pigment leakage vs ethanol concentration",
  },
  {
    id: 21,
    subtopic: "Permeability & Specific Substances",
    front: "How do <strong>extreme pH</strong> or <strong>high temperatures</strong> damage the cell membrane?",
    back: "They cause the membrane proteins to <strong>denature</strong>.",
    image: "./assets/page20_img2.jpeg",
    imageAlt: "Beetroot Setup A 0°C clear vs Setup B 70°C red pigment leaked",
  },

  // Subtopic 3: Osmosis
  {
    id: 22,
    subtopic: "Osmosis",
    front: "Define <strong>osmosis</strong>.",
    back: "The net movement of water across a <strong>differentially permeable membrane</strong> from a region of <strong>higher water potential</strong> to <strong>lower water potential</strong>.",
    image: "./assets/page18_img2.jpeg",
    imageAlt: "Osmosis — net water movement across differentially permeable membrane",
  },
  {
    id: 23,
    subtopic: "Osmosis",
    front: "Does osmosis require energy?",
    back: "<strong>No</strong>, it is a completely <strong>passive</strong> process.",
    image: "./assets/page18_img2.jpeg",
    imageAlt: "Passive osmosis — no energy input",
  },
  {
    id: 24,
    subtopic: "Osmosis",
    front: "What is the core rule for predicting the direction of water movement in osmosis?",
    back: "<strong>Water follows the solute</strong> → it moves toward the higher solute concentration.",
    image: "./assets/page18_img2.jpeg",
    imageAlt: "Water moves toward higher solute concentration",
  },
  {
    id: 25,
    subtopic: "Osmosis",
    front: "What is the water potential of <strong>pure water</strong>?",
    back: "<strong>0 kPa</strong>.",
    image: "./assets/page18_img1.jpeg",
    imageAlt: "Water potential scale — pure water at 0 kPa",
  },
  {
    id: 26,
    subtopic: "Osmosis",
    front: "How does adding a solute affect water potential?",
    back: "It <strong>lowers</strong> the water potential (makes it a negative value).",
    image: "./assets/page18_img1.jpeg",
    imageAlt: "Solute lowers water potential — credit-card analogy",
  },

  // Subtopic 4: Active Transport & Phagocytosis
  {
    id: 27,
    subtopic: "Active Transport & Phagocytosis",
    front: "What transport mechanism is used for <strong>nitrates</strong> entering root hair cells (moving ↑ against the concentration gradient)?",
    back: "<strong>Active transport</strong> (→ requires carrier proteins + energy).",
    image: "./assets/page33_img1.jpeg",
    imageAlt: "Active transport — carrier protein powered by energy",
  },
  {
    id: 28,
    subtopic: "Active Transport & Phagocytosis",
    front: "What is <strong>phagocytosis</strong>?",
    back: "The active process of engulfing <strong>large particles or food</strong> (too large to transport by diffusion/active transport).",
    image: "./assets/page34_img1.jpeg",
    imageAlt: "Phagocytosis — engulfing large particles",
  },
  {
    id: 29,
    subtopic: "Active Transport & Phagocytosis",
    front: "What physical property of the cell membrane enables phagocytosis?",
    back: "The membrane's <strong>fluidity</strong>.",
    image: "./assets/page34_img1.jpeg",
    imageAlt: "Membrane fluidity enables folding and engulfment",
  },
  {
    id: 30,
    subtopic: "Active Transport & Phagocytosis",
    front: "Does phagocytosis require energy?",
    back: "<strong>Yes</strong>, it uses energy (from respiration) to power <strong>membrane folding</strong>.",
    image: "./assets/page34_img1.jpeg",
    imageAlt: "Phagocytosis requires ATP from respiration",
  },
  {
    id: 31,
    subtopic: "Active Transport & Phagocytosis",
    front: "During phagocytosis, what does the cell membrane form to initially enclose the particle?",
    back: "<strong>Pseudopodia</strong> (outward extensions / infoldings of the membrane).",
    image: "./assets/page34_img1.jpeg",
    imageAlt: "Pseudopodia surround foreign particle",
  },
  {
    id: 32,
    subtopic: "Active Transport & Phagocytosis",
    front: "Once engulfed, what structure traps the foreign particle inside the cell?",
    back: "A <strong>vacuole</strong> (or vesicle).",
    image: "./assets/page34_img1.jpeg",
    imageAlt: "Food vacuole traps engulfed particle",
  },
  {
    id: 33,
    subtopic: "Active Transport & Phagocytosis",
    front: "Which organelle fuses with the vacuole to catalyze digestion of the engulfed particle?",
    back: "A <strong>lysosome</strong> (which contains digestive <strong>enzymes</strong> that catalyze digestion).",
    image: "./assets/page34_img1.jpeg",
    imageAlt: "Lysosome fuses with vacuole to catalyze digestion of contents",
  },
  {
    id: 34,
    subtopic: "Active Transport & Phagocytosis",
    front: "How do white blood cells engulf <strong>bacteria</strong>?",
    back: "<strong>Phagocytosis</strong> (membrane folding into pseudopodia).",
    image: "./assets/page35_img1.jpeg",
    imageAlt: "White blood cell / Amoeba engulfing particles",
  },
  {
    id: 35,
    subtopic: "Active Transport & Phagocytosis",
    front: "How do unicellular organisms like <strong>Amoeba</strong> engulf <strong>food particles</strong>?",
    back: "<strong>Phagocytosis</strong> (membrane folding).",
    image: "./assets/page35_img1.jpeg",
    imageAlt: "Amoeba phagocytosis of food particle",
  },
];
