import { MEMBRANE_QUIZ_EXERCISES } from "./membraneQuizExercises.js";

/** Ch 3 Membrane transport — concept checks from course notes (MCQ answer key aligned). */
export const QUIZ_SECTIONS = [
  { id: "fluid-mosaic", label: "Fluid mosaic & permeability", labelZh: "流動鑲嵌與滲透性" },
  { id: "phospholipid", label: "Phospholipid & proteins", labelZh: "磷脂與膜蛋白" },
  { id: "osmosis", label: "Osmosis", labelZh: "滲透" },
  { id: "active-phago", label: "Active transport & phagocytosis", labelZh: "主動運輸與吞噬" },
];

export const MEMBRANE_QUIZ = [
  // —— Fluid mosaic & differential permeability ——
  {
    id: "fm-1",
    section: "fluid-mosaic",
    difficulty: "Foundation",
    stem: "Which of the following is an example of a small, non-polar molecule that can diffuse through the phospholipid bilayer? (non-polar = “like oil”)",
    options: [
      { key: "A", text: "Water" },
      { key: "B", text: "Oxygen" },
      { key: "C", text: "Glucose" },
      { key: "D", text: "Sodium ions" },
    ],
    answer: "B",
    hint: "Non-polar molecules are lipid-soluble (hydrophobic) and pass through the bilayer directly.",
    image: { src: "./assets/page02_img2.jpeg", alt: "Differential permeability across the phospholipid bilayer", caption: "Fig · Small non-polar molecules cross the bilayer; polar and charged species need proteins." },
  },
  {
    id: "fm-2",
    section: "fluid-mosaic",
    difficulty: "Foundation",
    stem: "Which of the following molecules requires a protein channel to cross the cell membrane?",
    options: [
      { key: "A", text: "Carbon dioxide" },
      { key: "B", text: "Fatty acids" },
      { key: "C", text: "Sodium ions" },
      { key: "D", text: "Glycerol" },
    ],
    answer: "C",
    hint: "Small ions carry charge and cannot pass the hydrophobic core without transport proteins.",
  },
  {
    id: "fm-3",
    section: "fluid-mosaic",
    difficulty: "Foundation",
    stem: "What is the main function of the phospholipid bilayer in the cell membrane?",
    options: [
      { key: "A", text: "To provide energy for cellular activities" },
      { key: "B", text: "To act as a barrier controlling materials moving in and out of the cell" },
      { key: "C", text: "To synthesize proteins" },
      { key: "D", text: "To store genetic material" },
    ],
    answer: "B",
    hint: "The bilayer provides differential permeability — a selective barrier.",
  },
  {
    id: "fm-4",
    section: "fluid-mosaic",
    difficulty: "Foundation",
    stem: "Which of the following best describes the term “fluid” in the Fluid Mosaic Model?",
    options: [
      { key: "A", text: "Embedded proteins are rigid." },
      { key: "B", text: "Phospholipids can move laterally." },
      { key: "C", text: "The cell membrane is impermeable." },
      { key: "D", text: "Membrane proteins are fixed in position." },
    ],
    answer: "B",
    hint: "“Fluid” refers to lateral movement of lipids and proteins, giving flexibility.",
    image: {
      src: "./assets/page01_img3.jpeg",
      alt: "Soup analogy for fluid mosaic model — creamy soup (phospholipid bilayer) with oil droplets (proteins) that move laterally",
      caption: "Fig · Fluid mosaic soup analogy — bilayer as soup; proteins as oil droplets moving on the surface.",
    },
  },
  {
    id: "fm-5",
    section: "fluid-mosaic",
    difficulty: "Foundation",
    stem: "What is the characteristic of non-polar molecules that allows them to pass through the phospholipid bilayer?",
    options: [
      { key: "A", text: "They are large and hydrophilic." },
      { key: "B", text: "They are small and hydrophobic." },
      { key: "C", text: "They are charged." },
      { key: "D", text: "They are polar." },
    ],
    answer: "B",
    hint: "Like dissolves like — hydrophobic tails accept non-polar, lipid-soluble molecules.",
  },
  {
    id: "fm-6",
    section: "fluid-mosaic",
    difficulty: "Foundation",
    stem: "Which of the following is NOT a property of the cell membrane?",
    options: [
      { key: "A", text: "Differential permeability" },
      { key: "B", text: "Flexibility" },
      { key: "C", text: "Mosaic pattern of proteins" },
      { key: "D", text: "Rigid and immovable structure" },
    ],
    answer: "D",
    hint: "The membrane is flexible and dynamic — not rigid.",
  },
  {
    id: "fm-7",
    section: "fluid-mosaic",
    difficulty: "Standard",
    stem: "What is the role of proteins in the cell membrane?",
    options: [
      { key: "A", text: "To allow the passage of small, non-polar molecules" },
      { key: "B", text: "To transport large or charged molecules across the membrane" },
      { key: "C", text: "To synthesize carbohydrates" },
      { key: "D", text: "To provide energy" },
    ],
    answer: "B",
    hint: "Proteins include channels and carriers for substances that cannot cross the bilayer alone.",
    image: {
      src: "./assets/page09_channel_carrier.png",
      alt: "Protein channel and carrier protein in phospholipid bilayer — facilitated transport of polar and charged molecules",
      caption:
        "Fig · Channel protein (open pore) vs carrier protein (shape change) — transport substances that cannot cross the bilayer alone.",
    },
  },
  {
    id: "fm-8",
    section: "fluid-mosaic",
    difficulty: "Standard",
    stem: "Which of the following molecules is transported via membrane folding?",
    options: [
      { key: "A", text: "Oxygen" },
      { key: "B", text: "Water" },
      { key: "C", text: "Starch" },
      { key: "D", text: "Glucose" },
    ],
    answer: "C",
    hint: "Large molecules such as starch need endocytosis/phagocytosis (membrane folding), not simple diffusion.",
  },
  {
    id: "fm-9",
    section: "fluid-mosaic",
    difficulty: "Foundation",
    stem: "Which part of the cell membrane is hydrophobic?",
    options: [
      { key: "A", text: "The phosphate head of the phospholipids" },
      { key: "B", text: "The protein channels" },
      { key: "C", text: "The fatty acid tails of the phospholipids" },
      { key: "D", text: "The carbohydrate molecules" },
    ],
    answer: "C",
    hint: "Tails are non-polar and face inward in the bilayer.",
    image: {
      src: "./assets/page08_img2_crosssection.jpeg",
      alt: "Phospholipid bilayer cross-section with hydrophilic head and hydrophobic tail labels",
      caption:
        "Fig 3b (cross-section) · Hydrophilic head; hydrophobic tails face inward between the two layers.",
    },
  },
  {
    id: "fm-10",
    section: "fluid-mosaic",
    difficulty: "Foundation",
    stem: "What does the term “mosaic” in the Fluid Mosaic Model refer to?",
    options: [
      { key: "A", text: "The flexibility of the phospholipid bilayer" },
      { key: "B", text: "The arrangement of proteins embedded in the membrane" },
      { key: "C", text: "The selective permeability of the membrane" },
      { key: "D", text: "The movement of ions across the membrane" },
    ],
    answer: "B",
    hint: "Mosaic = scattered pattern of embedded membrane proteins.",
    image: {
      src: "./assets/page01_img4.jpeg",
      alt: "Mosaic tile analogy — scattered black hex tiles (left) and clustered flower-like patterns (right) on a white hex grid, representing membrane proteins embedded among phospholipids",
      caption:
        "Fig · Mosaic analogy — membrane proteins scattered or clustered in the phospholipid bilayer, like tiles in a mosaic floor.",
    },
  },
  {
    id: "fm-fold",
    section: "fluid-mosaic",
    difficulty: "Standard",
    stem: "Membrane folding is enabled by which property of the cell membrane?",
    options: [
      { key: "A", text: "“Fluid” — fluidity of the membrane" },
      { key: "B", text: "“Mosaic” — mosaic pattern alone" },
      { key: "C", text: "Both fluid and mosaic equally" },
      { key: "D", text: "Rigidity of the bilayer" },
    ],
    answer: "A",
    hint: "Infolding for feeding (e.g. Amoeba) needs a flexible, fluid membrane.",
  },

  // —— Phospholipid, proteins, membrane damage ——
  {
    id: "pl-1",
    section: "phospholipid",
    difficulty: "Foundation",
    stem: "Which of the following components of a phospholipid is hydrophilic?",
    options: [
      { key: "A", text: "Fatty acid tails" },
      { key: "B", text: "Glycerol backbone only" },
      { key: "C", text: "Phosphate group" },
      { key: "D", text: "Both fatty acid tails and glycerol" },
    ],
    answer: "C",
    hint: "The phosphate-containing head interacts with water.",
    image: {
      src: "./assets/page08_img1.jpeg",
      alt: "Comparison of triglyceride and phospholipid structure with hydrophilic head and hydrophobic tails",
      caption:
        "Fig 3a · Triglyceride (fully hydrophobic) vs phospholipid (hydrophilic head + hydrophobic tails).",
    },
  },
  {
    id: "pl-2",
    section: "phospholipid",
    difficulty: "Foundation",
    stem: "What is the main reason why phospholipids form a bilayer in water?",
    options: [
      { key: "A", text: "Hydrophobic tails are attracted to water." },
      { key: "B", text: "Hydrophilic heads interact with water, while hydrophobic tails avoid it." },
      { key: "C", text: "Both heads and tails are hydrophilic." },
      { key: "D", text: "Phospholipids dissolve completely in water." },
    ],
    answer: "B",
    hint: "Amphipathic structure drives tail-to-tail bilayer formation.",
  },
  {
    id: "pl-3",
    section: "phospholipid",
    difficulty: "Standard",
    stem: "Which of the following molecules is transported by carrier proteins?",
    options: [
      { key: "A", text: "Small, non-polar molecules" },
      { key: "B", text: "Large, polar molecules" },
      { key: "C", text: "Water-soluble ions via channels only" },
      { key: "D", text: "Gases like oxygen and carbon dioxide" },
    ],
    answer: "B",
    hint: "Carriers change shape; large polar molecules often use carrier/transport proteins.",
    image: { src: "./assets/page09_img3.jpeg", alt: "Membrane protein types and functions", caption: "Fig · Channel vs carrier proteins — carriers use shape change." },
  },
  {
    id: "pl-4",
    section: "phospholipid",
    difficulty: "Foundation",
    stem: "Which type of membrane protein acts like an “ID card” for cell identification?",
    options: [
      { key: "A", text: "Channel proteins" },
      { key: "B", text: "Glycoproteins" },
      { key: "C", text: "Carrier proteins" },
      { key: "D", text: "Receptor proteins" },
    ],
    answer: "B",
    hint: "Glycoproteins act as antigens for cell recognition.",
    image: {
      src: "./assets/page09_img3.jpeg",
      alt: "Membrane protein functions: metabolic catalyst, material exchange, reception and recognition",
      caption: "Fig 4 · Membrane protein roles — enzymes; channel & carrier proteins; receptor & glycoprotein (cell ID).",
    },
  },
  {
    id: "pl-5",
    section: "phospholipid",
    difficulty: "Foundation",
    stem: "What happens to a protein in the cell membrane at high temperatures?",
    options: [
      { key: "A", text: "It becomes more rigid." },
      { key: "B", text: "It denatures." },
      { key: "C", text: "It becomes impermeable." },
      { key: "D", text: "It thickens." },
    ],
    answer: "B",
    hint: "High temperature denatures proteins and destabilizes the lipid bilayer.",
    image: { src: "./assets/page20_img2.jpeg", alt: "Beetroot Setup A 0°C vs Setup B 70°C — pigment leaks at high temperature", caption: "Fig 13 · Setup A (0°C) clear water; Setup B (70°C) pigment leaked — membrane damaged by heat." },
  },
  {
    id: "pl-6",
    section: "phospholipid",
    difficulty: "Standard",
    stem: "Which factor can denature membrane proteins but not dissolve the lipid bilayer?",
    options: [
      { key: "A", text: "Organic solvents" },
      { key: "B", text: "Detergents" },
      { key: "C", text: "Extreme pH" },
      { key: "D", text: "Adding oil" },
    ],
    answer: "C",
    hint: "Organic solvents and detergents dissolve lipids; extreme pH mainly denatures proteins.",
  },
  {
    id: "pl-7",
    section: "phospholipid",
    difficulty: "Foundation",
    stem: "Which of the following is NOT a function of membrane proteins?",
    options: [
      { key: "A", text: "Speed up chemical reactions" },
      { key: "B", text: "Transport large molecules" },
      { key: "C", text: "Store genetic material" },
      { key: "D", text: "Act as receptors for chemical messengers" },
    ],
    answer: "C",
    hint: "Genetic material is stored in the nucleus, not the membrane.",
  },
  {
    id: "pl-8",
    section: "phospholipid",
    difficulty: "Foundation",
    stem: "What is the role of enzymes in the cell membrane?",
    options: [
      { key: "A", text: "To provide structural support" },
      { key: "B", text: "To speed up chemical reactions" },
      { key: "C", text: "To transport molecules across the membrane" },
      { key: "D", text: "To regulate cell recognition" },
    ],
    answer: "B",
    hint: "Membrane-bound enzymes are metabolic catalysts.",
  },
  {
    id: "pl-9",
    section: "phospholipid",
    difficulty: "Foundation",
    stem: "Why is the phospholipid bilayer described as “tail-to-tail”?",
    options: [
      { key: "A", text: "Hydrophilic heads face each other." },
      { key: "B", text: "Hydrophobic tails face each other inside the bilayer." },
      { key: "C", text: "Hydrophilic heads face the cytoplasm only." },
      { key: "D", text: "Hydrophobic tails face the extracellular fluid." },
    ],
    answer: "B",
    hint: "Inner core = hydrophobic tails; heads face aqueous sides.",
    image: {
      src: "./assets/page08_img4.png",
      alt: "Phospholipid micelles and liposome bilayer in aqueous environment; reverse-micelles in lipidic environment",
      caption:
        "Fig · Liposome bilayer — hydrophobic tails meet in the middle (tail-to-tail); polar heads face aqueous sides.",
    },
  },
  {
    id: "pl-10",
    section: "phospholipid",
    difficulty: "Standard",
    stem: "Which of the following factors can dissolve the lipid bilayer?",
    options: [
      { key: "A", text: "Mechanical stress" },
      { key: "B", text: "Detergents" },
      { key: "C", text: "Extreme pH" },
      { key: "D", text: "High temperature only" },
    ],
    answer: "B",
    hint: "Detergents (and organic solvents) dissolve lipids and break protein–lipid interactions.",
  },

  // —— Osmosis (concept checks + applied diagrams) ——
  {
    id: "os-1",
    section: "osmosis",
    difficulty: "Foundation",
    stem: "What is the primary requirement for osmosis to occur?",
    options: [
      { key: "A", text: "Light" },
      { key: "B", text: "Temperature" },
      { key: "C", text: "Differentially permeable membrane" },
      { key: "D", text: "High solute concentration only" },
    ],
    answer: "C",
    hint: "Also need a water potential difference between the two regions.",
    image: { src: "./assets/page18_img2.jpeg", alt: "Osmosis across a differentially permeable membrane", caption: "Fig · Net water moves along the water potential gradient." },
  },
  {
    id: "os-2",
    section: "osmosis",
    difficulty: "Foundation",
    stem: "Which solution has the highest water potential?",
    options: [
      { key: "A", text: "Pure water" },
      { key: "B", text: "5% sucrose solution" },
      { key: "C", text: "10% sucrose solution" },
      { key: "D", text: "Saltwater" },
    ],
    answer: "A",
    hint: "Pure water ψ ≈ 0 kPa; adding solute lowers ψ.",
    image: { src: "./assets/page18_img1.jpeg", alt: "Water potential values table", caption: "Fig · Pure water 0 kPa; more solute → more negative ψ." },
  },
  {
    id: "os-3",
    section: "osmosis",
    difficulty: "Foundation",
    stem: "In the context of osmosis, what does a lower water potential indicate?",
    options: [
      { key: "A", text: "Higher solute concentration" },
      { key: "B", text: "Lower solute concentration" },
      { key: "C", text: "Equal solute concentration" },
      { key: "D", text: "No solute" },
    ],
    answer: "A",
    hint: "More solute → less free water → lower (more negative) ψ.",
  },
  {
    id: "os-4",
    section: "osmosis",
    difficulty: "Foundation",
    stem: "During osmosis, water moves from:",
    options: [
      { key: "A", text: "High solute concentration to low solute concentration" },
      { key: "B", text: "Low water potential to high water potential" },
      { key: "C", text: "High water potential to low water potential" },
      { key: "D", text: "Low solute concentration to high solute concentration (solute moves)" },
    ],
    answer: "C",
    hint: "Water follows solute — net water moves toward higher solute (lower ψ).",
  },
  {
    id: "os-5",
    section: "osmosis",
    difficulty: "Foundation",
    stem: "What is the role of a differentially permeable membrane in osmosis?",
    options: [
      { key: "A", text: "It allows solute movement" },
      { key: "B", text: "It blocks all substances" },
      { key: "C", text: "It allows water to pass while restricting many solutes" },
      { key: "D", text: "It facilitates active transport" },
    ],
    answer: "C",
    hint: "Solute generally does not cross in osmosis — only water net movement.",
  },
  {
    id: "os-6",
    section: "osmosis",
    difficulty: "Foundation",
    stem: "Which of the following is true about osmosis?",
    options: [
      { key: "A", text: "It requires energy" },
      { key: "B", text: "It is an active process" },
      { key: "C", text: "It is a passive process" },
      { key: "D", text: "It involves net movement of solutes" },
    ],
    answer: "C",
    hint: "No ATP needed — passive net movement of water.",
  },
  {
    id: "os-7",
    section: "osmosis",
    difficulty: "Standard",
    stem: "If a beetroot cell leaks pigment (“juice leaked”), will osmosis still occur across that membrane?",
    options: [
      { key: "A", text: "Yes — pigment leakage does not matter" },
      { key: "B", text: "No — the membrane is damaged and no longer differentially permeable" },
      { key: "C", text: "Yes — osmosis only needs pigment" },
      { key: "D", text: "No — osmosis requires pigment retention" },
    ],
    answer: "B",
    hint: "Damaged membrane loses differential permeability.",
    image: { src: "./assets/page20_img2.jpeg", alt: "Beetroot Setup A 0°C vs Setup B 70°C — pigment leaks at high temperature", caption: "Fig 13 · Damaged membrane (70°C) → pigment leaks; osmosis requirements fail." },
  },
  {
    id: "os-8",
    section: "osmosis",
    difficulty: "Foundation",
    stem: "Which statement is correct regarding water potential?",
    options: [
      { key: "A", text: "It increases with solute concentration" },
      { key: "B", text: "It decreases with solute concentration" },
      { key: "C", text: "It is unaffected by solute" },
      { key: "D", text: "It is always positive in cells" },
    ],
    answer: "B",
    hint: "Dissolved solute lowers water potential.",
  },
  {
    id: "os-9",
    section: "osmosis",
    difficulty: "Standard",
    stem: "If a potato is boiled, will osmosis still occur through its cell membranes?",
    options: [
      { key: "A", text: "Yes — the cell wall remains intact" },
      { key: "B", text: "No — the cell membrane is damaged" },
      { key: "C", text: "Yes — boiling does not affect osmosis" },
      { key: "D", text: "No — boiling increases water potential" },
    ],
    answer: "B",
    hint: "Boiling denatures membrane proteins and disrupts the bilayer.",
  },
  {
    id: "os-10",
    section: "osmosis",
    difficulty: "Foundation",
    stem: "Which condition will stop osmosis?",
    options: [
      { key: "A", text: "Equal water potential on both sides" },
      { key: "B", text: "High temperature only" },
      { key: "C", text: "Low temperature only" },
      { key: "D", text: "Increased light intensity" },
    ],
    answer: "A",
    hint: "No ψ difference → no net water movement (individual molecules still move).",
  },
  {
    id: "os-cap",
    section: "osmosis",
    difficulty: "Applied",
    stem: "In the osmosis investigation below, concentrated sucrose solution X is inside the dialysis tubing and dilute solution Y is outside. After 30 minutes the liquid level in the glass tube rises because:",
    options: [
      { key: "A", text: "Water molecules pass from X to Y only." },
      { key: "B", text: "Water molecules pass from Y to X only." },
      { key: "C", text: "More water molecules pass from Y to X than from X to Y" },
      { key: "D", text: "More water molecules pass from X to Y than from Y to X" },
    ],
    answer: "C",
    hint: "Net water moves into the more concentrated solution (lower ψ inside X).",
    image: { src: "./assets/page19_img1.png", alt: "Osmosis setup with dialysis tubing and capillary tube", caption: "Fig · Capillary rises when net water enters tubing (Y → X)." },
  },
  {
    id: "os-rbc",
    section: "osmosis",
    difficulty: "Applied",
    stem: "The photomicrographs show red blood cells in sucrose solutions A, B and C (A = normal, B = crenated, C = swollen/haemolysed). Which arranges sucrose concentrations in descending order?",
    options: [
      { key: "A", text: "A > C > B" },
      { key: "B", text: "B > A > C" },
      { key: "C", text: "C > A > B" },
      { key: "D", text: "C > B > A" },
    ],
    answer: "B",
    hint: "Crenation = hypertonic (highest sucrose); swelling = hypotonic (lowest).",
    image: { src: "./assets/page22_img1.jpeg", alt: "RBC in sucrose solutions A B C", caption: "Fig · B hypertonic (crenated) · A isotonic · C hypotonic (swollen)." },
  },
  {
    id: "os-visk",
    section: "osmosis",
    difficulty: "Applied",
    stem: "Visking tubing contains solution X; solution Y is outside. Initial mass of the tubing 12.0 g → final mass 9.5 g. These results occur when:",
    options: [
      { key: "A", text: "X is 5% sucrose and Y is distilled water" },
      { key: "B", text: "X is 5% sucrose and Y is 10% sucrose" },
      { key: "C", text: "X is 10% sucrose and Y is 5% sucrose" },
      { key: "D", text: "X is 10% sucrose and Y is distilled water" },
    ],
    answer: "C",
    hint: "Mass loss = net water leaves tubing → outside less concentrated than inside.",
    image: { src: "./assets/page22_img2.png", alt: "Visking tubing osmosis experiment", caption: "Fig · Water leaves tubing when outside ψ is higher (less concentrated)." },
  },
  {
    id: "os-gut",
    section: "osmosis",
    difficulty: "Applied",
    stem: "Which part of the human digestive system absorbs the greatest amount of water?",
    options: [
      { key: "A", text: "Stomach" },
      { key: "B", text: "Small intestine" },
      { key: "C", text: "Large intestine" },
      { key: "D", text: "All parts absorb the same amount" },
    ],
    answer: "C",
    hint: "Most water absorption occurs in the large intestine.",
    image: { src: "./assets/page23_img1.jpeg", alt: "Human digestive system numbered diagram", caption: "Fig · Large intestine absorbs the most water (water follows solute)." },
  },
  {
    id: "os-pot-m",
    section: "osmosis",
    difficulty: "Applied",
    stem: "The graph shows percentage change in mass of potato cylinders in salt solutions (0–8%). The water potential of the potato tissue is the same as which salt concentration?",
    options: [
      { key: "A", text: "About 2%" },
      { key: "B", text: "About 5.8% (where % mass change = 0)" },
      { key: "C", text: "About 8%" },
      { key: "D", text: "0% only" },
    ],
    answer: "B",
    hint: "Isotonic point = no net water movement = 0% mass change.",
    image: { src: "./assets/page24_img1.jpeg", alt: "Potato mass change vs salt concentration graph", caption: "Fig · Isotonic ≈ 5.8% salt (line crosses 0% mass change)." },
  },
  {
    id: "os-pot-l",
    section: "osmosis",
    difficulty: "Applied",
    stem: "Potato strips were placed in salt solutions of different concentrations. At which concentration is strip length expected to remain unchanged?",
    options: [
      { key: "A", text: "0.0 arbitrary units" },
      { key: "B", text: "0.1 arbitrary units" },
      { key: "C", text: "0.3 arbitrary units" },
      { key: "D", text: "0.6 arbitrary units" },
    ],
    answer: "C",
    hint: "Unchanged length = isotonic — read the chart where mean length is constant.",
    image: { src: "./assets/page25_img2.png", alt: "Bar chart potato strip length vs salt concentration", caption: "Fig · Length unchanged at 0.3 arbitrary units." },
  },
  {
    id: "os-17",
    section: "osmosis",
    difficulty: "Standard",
    stem: "Which statement is true about the direction of net water movement in osmosis?",
    options: [
      { key: "A", text: "From low to high solute concentration (solute moves)" },
      { key: "B", text: "From high to low solute concentration" },
      { key: "C", text: "From low to high water potential" },
      { key: "D", text: "From high to low water potential" },
    ],
    answer: "D",
    hint: "Net water moves toward lower ψ (more solute).",
  },
  {
    id: "os-18",
    section: "osmosis",
    difficulty: "Standard",
    stem: "Which factor is NOT required for osmosis?",
    options: [
      { key: "A", text: "Differentially permeable membrane" },
      { key: "B", text: "Water potential difference" },
      { key: "C", text: "Solute movement across the membrane" },
      { key: "D", text: "Presence of water" },
    ],
    answer: "C",
    hint: "Solute does not cross the membrane in osmosis.",
  },
  {
    id: "os-19",
    section: "osmosis",
    difficulty: "Standard",
    stem: "What is the immediate effect of placing a cell in a solution with lower water potential than the cell?",
    options: [
      { key: "A", text: "Cell shrinks" },
      { key: "B", text: "Cell swells" },
      { key: "C", text: "No change in cell size" },
      { key: "D", text: "Cell always bursts" },
    ],
    answer: "A",
    hint: "Water leaves the cell toward the hypertonic surroundings.",
  },
  {
    id: "os-20",
    section: "osmosis",
    difficulty: "Standard",
    stem: "When two solutions are separated by a differentially permeable membrane, water moves towards:",
    options: [
      { key: "A", text: "Higher water potential" },
      { key: "B", text: "Lower water potential" },
      { key: "C", text: "Lower solute concentration only" },
      { key: "D", text: "Equal solute on both sides" },
    ],
    answer: "B",
    hint: "Same as moving toward higher solute concentration.",
  },

  // —— Active transport & phagocytosis ——
  {
    id: "at-1",
    section: "active-phago",
    difficulty: "Foundation",
    stem: "What provides the energy required for active transport?",
    options: [
      { key: "A", text: "Oxygen directly" },
      { key: "B", text: "Enzymes alone" },
      { key: "C", text: "Energy from respiration (ATP)" },
      { key: "D", text: "Water potential gradient" },
    ],
    answer: "C",
    hint: "Respiration supplies ATP for carrier protein shape change.",
    image: { src: "./assets/page33_img1.jpeg", alt: "Active transport carrier protein shape change", caption: "Fig · Carrier uses energy from respiration to change shape." },
  },
  {
    id: "at-2",
    section: "active-phago",
    difficulty: "Foundation",
    stem: "Which of the following is required for active transport in cells?",
    options: [
      { key: "A", text: "Diffusion only" },
      { key: "B", text: "Carrier proteins" },
      { key: "C", text: "Lysosomes only" },
      { key: "D", text: "Phagocytosis" },
    ],
    answer: "B",
    hint: "Carrier proteins change shape to pump substances.",
  },
  {
    id: "at-3",
    section: "active-phago",
    difficulty: "Foundation",
    stem: "What is the role of carrier proteins in active transport?",
    options: [
      { key: "A", text: "To digest particles" },
      { key: "B", text: "To change shape and move molecules across the membrane" },
      { key: "C", text: "To engulf particles" },
      { key: "D", text: "To break down proteins outside the cell" },
    ],
    answer: "B",
    hint: "Different from channel proteins — carriers undergo conformational change.",
  },
  {
    id: "at-4",
    section: "active-phago",
    difficulty: "Foundation",
    stem: "Which of the following occurs during phagocytosis?",
    options: [
      { key: "A", text: "The cell engulfs large particles or food" },
      { key: "B", text: "The cell transports small ions by diffusion only" },
      { key: "C", text: "The cell uses channel proteins only" },
      { key: "D", text: "The cell releases enzymes outside only" },
    ],
    answer: "A",
    hint: "Phagocytosis = engulfing large material by membrane folding.",
    image: { src: "./assets/page34_img1.jpeg", alt: "Phagocytosis steps diagram", caption: "Fig · Pseudopodia → vacuole → lysosome digestion." },
  },
  {
    id: "at-5",
    section: "active-phago",
    difficulty: "Standard",
    stem: "What enables the formation of pseudopodia during phagocytosis?",
    options: [
      { key: "A", text: "Carrier protein activity alone" },
      { key: "B", text: "Membrane fluidity" },
      { key: "C", text: "Enzyme secretion only" },
      { key: "D", text: "Energy from respiration alone (without fluidity)" },
    ],
    answer: "B",
    hint: "Membrane must be fluid to fold inward; energy is also needed for the process.",
  },
  {
    id: "at-6",
    section: "active-phago",
    difficulty: "Standard",
    stem: "Which type of transport is used to absorb nitrates (nutrient ions) into root hair cells when soil concentration is low?",
    options: [
      { key: "A", text: "Diffusion" },
      { key: "B", text: "Active transport" },
      { key: "C", text: "Osmosis" },
      { key: "D", text: "Phagocytosis" },
    ],
    answer: "B",
    hint: "Uptake against the concentration gradient requires active transport.",
  },
  {
    id: "at-7",
    section: "active-phago",
    difficulty: "Foundation",
    stem: "What happens to the particle after it is engulfed by pseudopodia during phagocytosis?",
    options: [
      { key: "A", text: "It is digested immediately in the cytoplasm" },
      { key: "B", text: "It is enclosed in a vacuole" },
      { key: "C", text: "It is broken down by carrier proteins" },
      { key: "D", text: "It diffuses out again" },
    ],
    answer: "B",
    hint: "Food vacuole/vesicle forms before lysosome fusion.",
  },
  {
    id: "at-8",
    section: "active-phago",
    difficulty: "Foundation",
    stem: "What is the function of lysosomes in phagocytosis?",
    options: [
      { key: "A", text: "To provide energy for engulfing particles" },
      { key: "B", text: "To provide enzymes that catalyse digestion of the particle" },
      { key: "C", text: "To transport particles to the membrane" },
      { key: "D", text: "To release oxygen" },
    ],
    answer: "B",
    hint: "Lysosome enzymes catalyze digestion of contents in the vacuole.",
  },
  {
    id: "at-9",
    section: "active-phago",
    difficulty: "Standard",
    stem: "Which of the following is NOT involved in phagocytosis?",
    options: [
      { key: "A", text: "Formation of pseudopodia" },
      { key: "B", text: "Lysosome fusion with a vacuole" },
      { key: "C", text: "Diffusion of oxygen into the cytoplasm as the main uptake route" },
      { key: "D", text: "Digestion of engulfed particles" },
    ],
    answer: "C",
    hint: "O₂ enters by diffusion — not via phagocytosis.",
  },
  {
    id: "at-10",
    section: "active-phago",
    difficulty: "Standard",
    stem: "Which of the following is an example of phagocytosis?",
    options: [
      { key: "A", text: "Absorption of glucose in the intestine" },
      { key: "B", text: "White blood cells engulfing bacteria" },
      { key: "C", text: "Transport of ions into root hair cells" },
      { key: "D", text: "Diffusion of water into cells" },
    ],
    answer: "B",
    hint: "WBC phagocytosis is a classic HKDSE example.",
  },
  {
    id: "pg-bio",
    section: "active-phago",
    difficulty: "Standard",
    stem: "Which biomolecule is typically transported by phagocytosis rather than diffusion or active transport?",
    options: [
      { key: "A", text: "Glucose" },
      { key: "B", text: "Oxygen" },
      { key: "C", text: "Proteins (large particles)" },
      { key: "D", text: "Sodium ions" },
    ],
    answer: "C",
    hint: "Large polymers/particles need engulfing.",
  },
  {
    id: "pg-not",
    section: "active-phago",
    difficulty: "Foundation",
    stem: "Which of the following is NOT a function of phagocytosis?",
    options: [
      { key: "A", text: "Nutrition by Amoeba through engulfing food" },
      { key: "B", text: "White blood cells engulf and kill bacteria" },
      { key: "C", text: "Transport of oxygen into cells" },
      { key: "D", text: "Removal of dead cells and debris" },
    ],
    answer: "C",
    hint: "Gases cross by diffusion through the bilayer.",
  },
  {
    id: "pg-amoeba",
    section: "active-phago",
    difficulty: "Applied",
    stem: "The diagram shows a unicellular organism engulfing a food particle. The food can enter because:",
    stemZh: "圖示顯示單細胞生物吞噬食物粒子。食物能進入細胞是因為：",
    options: [
      { key: "A", text: "(1) and (2) only — movement toward food and fluidity", textZh: "(1) 及 (2) only — 向食物移動及流動性" },
      { key: "B", text: "(1) and (3) only", textZh: "(1) 及 (3) only" },
      { key: "C", text: "(2) and (3) only — fluidity and mosaic pattern", textZh: "(2) 及 (3) only — 流動性及馬賽克排列" },
      { key: "D", text: "(1), (2) and (3)", textZh: "(1)、(2) 及 (3)" },
    ],
    answer: "C",
    hint: "Engulfing needs membrane fluidity (folding); mosaic alone is not enough. Movement toward food is not why engulfing works.",
    image: { src: "./assets/page35_img1.jpeg", alt: "Amoeba engulfing food particle into vacuole", caption: "Fig · Phagocytosis — membrane fluidity enables infolding (Amoeba MCQ: 2 & 3)." },
  },
  ...MEMBRANE_QUIZ_EXERCISES,
];
